name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clean before compilation
        run: make clean

      - name: Checking every libs
        run: ls -lh lib/

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compile
        run: make compile

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Run tests with xvfb
        run: |
          xvfb-run --auto-servernum make test_gui

      - name: Run tests without GUI
        run: make test_no_gui
